services:
  fastapi:
    container_name: fastapi_openai_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped
